services:
  database:
    image: postgres:18-alpine
    container_name: bookstore_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Adicione esta linha:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: